# This rule is not used by the project simple-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.amir.local resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simple-operator
    app.kubernetes.io/managed-by: kustomize
  name: miniapp-viewer-role
rules:
- apiGroups:
  - apps.amir.local
  resources:
  - miniapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.amir.local
  resources:
  - miniapps/status
  verbs:
  - get
